### ISSUE TITLE
Could I get a key with Fileset Permissions

### ISSUE THREAD

**Issue by ericop** [digitalbiblesociety/dbp#9]
Hello,
I'm currently working on trying to write an open source Bible Reading Plan app similar to [DJ Bible Reading Plan](https://play.google.com/store/apps/details?id=huss.john.djbible&hl=en_US) which will allow both text and audio as you track your way through the bible in your language of choice.

I created an account and an API Key but is does not have permissions:

```
https://api.dbp4.org/bibles/filesets/ENGESV/ROM/2?v=4&key=LlRnSwXgqCurldfB6xS1g3dr
```
```json
{
    "error": {
        "message": "The Fileset exists, but no Permissions were found for your current key",
        "status code": 403,
        "action": ""
    }
}
```

Trying to use tech for Jesus glory and my joy,
EricOP
`eric.op.johnson` `<at>` `gmail.com`

**Comment by ericop** [comment]
@jonBitgood  could you shoot me a reply so I know the best way to get a hold of the correct people in your ministry to get Read-Access approval for my API key? 

I've tried emailing `info` `<at>` `dbp4.org` and `access` `<at>` `dbp4.org` , both of which are recommend contact points in your docs, but both returned `Address not found` from your mail server. I'm running out of ideas on how to reach out, and a little bit flustered.

Trying to find a way forward with your grace and The Fathers, 😉 
EricOP

**Comment by confirmed** [comment]
Hey @ericop, I'm not managing access for the API atm but if you email Alan Hooker adhooker@fcbhmail.org he should be able to hook you up with one.

In the meantime here's a test key:
30vs9XCuVx1qbNWRC2XHSlZ1

**Comment by ericop** [comment]
@jonBitgood Thank you much! I'll reach out to Alan.
